#!/usr/bin/env python3
"""One-time migration: markdown backlog -> canonical JSON backlog (folder-per-ticket).

Reads backlog/tickets/CM-<n>-<slug>/{README.md, plan.md?, evidence.md?} and
ROADMAP.md, and writes:
  blueprint/v1/backlog/tickets/CM-<n>-<slug>/ticket.json   (structured ticket body)
  blueprint/v1/backlog/tickets/CM-<n>-<slug>/plan.md        (kept as a file if present)
  blueprint/v1/backlog/tickets/CM-<n>-<slug>/evidence.md    (kept as a file if present)
  blueprint/v1/backlog/roadmap.json                         (epics + board summaries + prose)

Folder-per-ticket (CM-58): README.md -> ticket.json, build artifacts stay as
files. Board ids that were roadmap-only line-items (no folder) become minimal
stub folders. After this, JSON is the source of truth and ROADMAP.md is
regenerated by scripts/gen_roadmap.py.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TICKETS_DIR = ROOT / "backlog" / "tickets"
OUT_DIR = ROOT / "blueprint" / "v1" / "backlog"
OUT_TICKETS = OUT_DIR / "tickets"

EMOJI_STATUS = {"✅": "done", "⬜": "todo", "🟦": "in_progress", "⏸️": "blocked"}


def norm_status(s):
    s = (s or "").lower()
    if "done" in s:
        return "done"
    if "blocked" in s:
        return "blocked"
    if "in progress" in s or "in_progress" in s:
        return "in_progress"
    return "todo"


def slugify(s, maxwords=6):
    words = re.sub(r"[^a-z0-9]+", " ", s.lower()).split()
    return "-".join(words[:maxwords]) or "ticket"


def meta(text, key):
    m = re.search(rf"^- \*\*{key}:\*\*\s*(.+)$", text, re.MULTILINE)
    return m.group(1).strip() if m else None


def section(text, heading):
    m = re.search(rf"^##\s+{re.escape(heading)}\s*\n(.*?)(?=^##\s|\Z)", text, re.MULTILINE | re.DOTALL)
    return m.group(1).strip() if m else None


def bullets(sec):
    if not sec:
        return []
    out = []
    for line in sec.splitlines():
        m = re.match(r"^- \[[ x]\]\s*(.+)$", line) or re.match(r"^-\s+(.+)$", line)
        if m:
            out.append(m.group(1).strip())
    return out


def migrate_ticket(folder, epic_of):
    text = (folder / "README.md").read_text(encoding="utf-8")
    tid = re.match(r"(CM-\d+)-", folder.name).group(1)
    tm = re.search(r"^#\s*CM-\d+:?\s*(.+)$", text, re.MULTILINE)
    title = tm.group(1).strip() if tm else folder.name
    ttype = (meta(text, "Type") or "task").split()[0].strip("`")
    t = {
        "id": tid,
        "title": title,
        "epic": epic_of.get(tid, ""),
        "type": ttype,
        "status": norm_status(meta(text, "Status")),
        "slug": folder.name[len(tid) + 1:],
        "acceptance_criteria": bullets(section(text, "Acceptance criteria")),
    }
    goal = section(text, "Goal")
    t["goal"] = goal if goal else title
    ver = section(text, "Verification")
    if ver:
        t["verification"] = ver
    notes = section(text, "Notes")
    if notes:
        t["notes"] = notes
    return t


def parse_roadmap():
    text = (ROOT / "ROADMAP.md").read_text(encoding="utf-8")
    preamble = text[: re.search(r"^##\s+Status overview", text, re.MULTILINE).start()].rstrip()

    overview = {}
    for m in re.finditer(r"^\|\s*([0-9A-Z])\s*\|\s*(.+?)\s*\|\s*([ABC])\s*\|\s*([^\s|]+)\s*\|$", text, re.MULTILINE):
        phase, name, track, emoji = m.groups()
        overview[phase] = {"short_name": name, "track": track, "status": EMOJI_STATUS.get(emoji, "todo")}

    first = re.search(r"^##\s+(Phase|Epic)\b", text, re.MULTILINE)
    body = text[first.start():]
    dec_split = re.split(r"^##\s+Decisions log\s*$", body, maxsplit=1, flags=re.MULTILINE)
    epics_blob = dec_split[0]
    decisions_md = dec_split[1].strip() if len(dec_split) > 1 else ""

    epics, summaries, board_state, epic_of = [], {}, {}, {}
    parts = re.split(r"^(##\s+(?:Phase|Epic)\b.*)$", epics_blob, flags=re.MULTILINE)
    for i in range(1, len(parts), 2):
        heading = parts[i].strip().lstrip("#").strip()
        sec = parts[i + 1]
        plabel = re.match(r"(?:Phase|Epic)\s+([0-9A-Z])\b", heading).group(1)
        desc_m = re.search(r"^\*(.+?)\*\s*$", sec, re.MULTILINE)
        description = desc_m.group(1).strip() if desc_m else ""
        exit_m = re.search(r"^\*\*Exit:\*\*\s*(.+)$", sec, re.MULTILINE)
        exit_txt = exit_m.group(1).strip() if exit_m else ""
        ov = overview.get(plabel, {})
        eid = re.sub(r"[^a-z0-9]+", "-", heading.lower()).strip("-")
        tickets = []
        for line in sec.splitlines():
            lm = re.match(r"^- \[([ x])\] `(CM-\d+)` (.+)$", line)
            if lm:
                checked, tid, summ = lm.group(1) == "x", lm.group(2), lm.group(3).strip()
                tickets.append(tid)
                summaries[tid] = summ
                board_state[tid] = checked
                epic_of[tid] = eid
        epics.append({
            "id": eid, "name": heading, "phase": plabel,
            "short_name": ov.get("short_name", heading), "track": ov.get("track", "A"),
            "status": ov.get("status", "todo"), "goal": description or heading,
            "tickets": tickets, "description": description, "exit": exit_txt,
        })

    decisions = [d.strip() for d in re.split(r"\n(?=- \*\*)", decisions_md) if d.strip()]
    roadmap = {
        "project": "CodeMaster", "version": "v1", "preamble": preamble,
        "epics": epics, "board_summaries": summaries, "decisions_log": decisions,
    }
    return roadmap, board_state, epic_of


def write_ticket(t, src_folder=None):
    dest = OUT_TICKETS / f"{t['id']}-{t['slug']}"
    dest.mkdir(parents=True, exist_ok=True)
    (dest / "ticket.json").write_text(json.dumps(t, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    if src_folder:  # keep build artifacts as files
        for art in ("plan.md", "evidence.md"):
            if (src_folder / art).exists():
                (dest / art).write_text((src_folder / art).read_text(encoding="utf-8"), encoding="utf-8")


def main():
    OUT_TICKETS.mkdir(parents=True, exist_ok=True)
    roadmap, board_state, epic_of = parse_roadmap()
    folders = {re.match(r"(CM-\d+)-", p.name).group(1): p
               for p in TICKETS_DIR.iterdir() if p.is_dir() and re.match(r"CM-\d+-", p.name)}

    migrated, stubs = 0, 0
    for tid in sorted(set(folders) | set(board_state), key=lambda s: int(s[3:])):
        if tid in folders:
            t = migrate_ticket(folders[tid], epic_of)
            write_ticket(t, src_folder=folders[tid])
            migrated += 1
        else:
            summ = roadmap["board_summaries"][tid]
            clean = re.sub(r"^[—–-]\s*", "", summ).strip()
            status = "done" if board_state[tid] else ("blocked" if "blocked" in summ.lower() else "todo")
            t = {"id": tid, "title": clean, "epic": epic_of.get(tid, ""), "type": "task",
                 "status": status, "slug": slugify(clean), "acceptance_criteria": [], "goal": clean,
                 "notes": "Roadmap line-item migrated as a stub; never elaborated as a folder ticket."}
            write_ticket(t)
            stubs += 1

    (OUT_DIR / "roadmap.json").write_text(json.dumps(roadmap, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"{migrated} migrated + {stubs} stubs = {migrated + stubs} ticket folders; "
          f"{len(roadmap['epics'])} epics, {len(roadmap['decisions_log'])} decisions")


if __name__ == "__main__":
    main()
